### ISSUE TITLE
code does not download with devtools.

### ISSUE THREAD

**Issue by cownr10r** [smn74/rankMANOVA#1]
Can someone help with this issue? Thanks in advance. 

<img width="407" alt="screen shot 2019-01-11 at 2 22 13 pm" src="https://user-images.githubusercontent.com/7209507/51057831-62f08980-15ac-11e9-8a50-527f1c1b5627.png">

**Comment by smn74** [comment]
I can't reproduce the error, it works fine on my machine. Can you give some more details on your R version, operating system etc?
